apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react-frontend
        image: netreact-front:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_ADDRESS
          value: "localhost:7153"
        - name: REACT_APP_AUTH_API_ADDRESS
          value: "localhost:7154"
        - name: REACT_APP_SERVERS_API_ADDRESS
          value: "localhost:7155"
        - name: REACT_APP_CHANNELS_API_ADDRESS
          value: "localhost:7156"
        - name: REACT_APP_MESSAGES_API_ADDRESS
          value: "localhost:7157"